INSERT INTO Product(title, subTitle, colorInfo, details, brand, price, stock, imageUrl)
    VALUES
    ("Nike Air Force 1'07", "Men's Shoes", "1 Colour", "The radiance lives on in the Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, classic comfort and bold details. This version lights up your hidden dragon with a fiery, clawed dubrae and scaly Swoosh logo.", "Nike", "175", "10", "air-force-1-07-shoes-1xp6CC.png"),
    ("Nike Air Alpha Trainer 5", "Men's Shoes", "4 Colours", "Finish your last rep with power and rack it with a roar that stuns the gym floor in the Nike Air Max Alpha Trainer 5. The Max Air cushioning offers comfortable stability for lifting whether it's a light or heavy day. A wide, flat base gives you enhanced stability and grip for all kinds of tough workouts without sacrificing style, as you roam from station to station and set to set.", "Nike", "125", "22", "air-max-alpha-trainer-5-workout-shoes-mgZ1Lq.png"),
    ("Nike Air Force 1'07 EasyOn", "Men's Shoes", "1 Colour", "Quicker than 1, 2, 3—the original hoops shoe lets you get going. This version of the AF-1 features Nike EasyOn technology for a hands-free experience. The flexible heel collapses when you step in then snaps back into place, making it easy to slip the shoe on and off. Add that to its clean, crisp leather and you've got ultimate wearability. Yeah, it's everything you love and then some.", "Nike", "150", "10", "air-force-1-07-easyon-shoes-rLFV2F.png"),
    ("Nike Air Max 90", "Men's Shoes", "3 Colours", "Lace up and feel the legacy in this champion running shoe that helped define the '90s. Worn by presidents, revolutionised through collabs and celebrated through rare colourways, its Waffle outsole, visible Nike Air cushioning and striking visuals keep it alive and well.", "Nike", "170", "10", "air-max-90-shoes-gpzwcp.png"),
    ("Nike Air Max Db", "Men's Shoes", "2 Colours", "Say hello to the next generation of Air technology. The Air Max Dn features our Dynamic Air unit system of dual-pressure tubes, creating a reactive sensation with every step. This results in a futuristic design that's comfortable enough to wear from day to night. Go ahead—Feel the Unreal.", "Nike", "210", "10", "air-max-dn-shoes-hZC5QK.png"),
    ("Air Jordan 1 Retro Low OG", "Men's Shoes", "1 Colour", "It's your familiar favourite, now infused with unique craft. The deconstructed upper gives you added comfort and a textured look. Underneath, classic Air cushioning adds quality to each and every step.", "Nike", "180", "10", "air-jordan-1-retro-low-og-shoes-ZgjTGq.png"),
    ("Nike Air Presto", "Men's Shoes", "3 Colours", "With a sleek design that's more comfortable than your favourite T-shirt, the Nike Air Presto is made to feel good and look fast. Its stretchy sleeve creates a cosy, sock-like fit while the super-soft foam adds spring to your step. Put them on and you'll never want to take them off.", "Nike", "126.99", "10", "air-presto-shoes-2SgNp1.png"),
    ("Air Jordan Mule", "Golf Shoes", "2 Colours", "Slide into pre- and post-game paradise, whether you're sailing to the 19th hole after a career low or ramping up for the round ahead in the all-new Jordan 1 G Mule. It's easily accessible, eye-poppingly eccentric and complete with timeless Jordan ethos and comfort.", "Nike", "175", "10", "air-jordan-mule-golf-shoes-DfhRjb.png");
